### ISSUE TITLE
"best practices" appears twice

### ISSUE THREAD

**Issue by daikema** [ilifu/ilifu_user_docs#31]
It appears both under "Getting Started" and under "Technical Documentation" despite being the same link.  Not sure which of the two we want to keep.

https://github.com/ilifu/ilifu_user_docs/blob/master/docs/_sidebar.md

**Comment by jeremysmith123** [comment]
I'd suggest keeping both - the more people read best practices the better

**Comment by daikema** [comment]
Load up the "Best Practices" under "Getting Started" and try to click the other best practices link with that page loads.

It winds up looking like a broken link ... he submenu in Getting Started stays expanded which makes it look like something is broken

**Comment by jeremysmith123** [comment]
I've repeated the markdown files to get around the broken link. I tried doing Embed Files from this link https://docsify.now.sh/embed-files, but this wasn't successful.

**Comment by jeremysmith123** [comment]
Best practices only appears once now.
